spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: library
    password: library_password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
